### ISSUE TITLE
feature requests for ingestion of TSV files

### ISSUE THREAD

**Issue by sformel-usgs** [gbif/metabarcoding-data-toolkit-ui#105]
1. allow CSV in addition to TSV
2. allow files to be named something other than `OTU_table.tsv, Taxonomy.tsv, Samples.tsv, and (optionally) Study.tsv` and have a feature to allow the user to map them if they are named differently. This is allowed in the IPT and it allows the user to preserve whatever naming convention works for them.

**Comment by thomasstjerne** [comment]
Thanks @sformel-usgs 

1. I think the delimiter will be auto detected already. So, CSVs should work.

2.  I will find a solution for this.
