### ISSUE TITLE
Fix error upon pressing "Create Darwin Core Archive"

### ISSUE THREAD

**Issue by tobiasgf** [gbif/metabarcoding-data-toolkit-ui#113]
Processing [example dataset 1](https://docs.gbif-uat.org/edna-tool-guide/en/#otu-table-template-1-excel-workbook)

With minimal metadata:

<img width="1244" alt="image" src="https://github.com/gbif/edna-tool-ui/assets/8543746/9d4e2c43-a3f4-4777-897f-d70fa3200147">

And proceeding to "Export", pressing "Create Darwin Core" gives this error (tested a couple of times by me, and also reported by a user)

<img width="1276" alt="image" src="https://github.com/gbif/edna-tool-ui/assets/8543746/e042e6dd-1d7d-4c5d-af70-8009d375b192">

**Comment by timrobertson100** [comment]
I tried it and [it worked](https://edna-tool.gbif-uat.org/dataset/b741a1ad-bbe0-4cc2-88d9-8d7aa7e3b9d5/export) in the tool and I was able to push it to the [UAT environment](https://www.gbif-uat.org/dataset/b94a5449-8d99-4673-8db8-f18d30818d63).

**Comment by MattBlissett** [comment]
Do the accounts need permissions in the Registry? i.e. organization namespace scope or similar.

**Comment by tobiasgf** [comment]
> I tried it and [it worked](https://edna-tool.gbif-uat.org/dataset/b741a1ad-bbe0-4cc2-88d9-8d7aa7e3b9d5/export) in the tool and I was able to push it to the [UAT environment](https://www.gbif-uat.org/dataset/b94a5449-8d99-4673-8db8-f18d30818d63).

My tests fail already at the "Create DWC" step, not "push to UAT"

**Comment by thomasstjerne** [comment]
Closing this, please re-open if it occurs again.
Isabel had a similar issue which related to cached responses that ignored auth headers. I fixed that with updated cache control headers.
