### ISSUE TITLE
Idea: Support upload of BIOM json

### ISSUE THREAD

**Issue by timrobertson100** [gbif/metabarcoding-data-toolkit-ui#115]
As I understand it, this tool allows the ability to map CSV and creates BIOM.

Perhaps we should support the ability to create a dataset from a BIOM format? Someone may have used tools like Phyloseq to create files that could then be loaded in here, thus minimising friction.

Note the IPT added functionality to upload a DwC-A, which is very useful, when originally the IPT was conceived as a tool to convert into DwC-A only. 

This came up as an idea in discussion with @sformel-usgs

**Comment by thomasstjerne** [comment]
After discussing this further with K. Silliman, it seems that users of [QIIME](https://qiime2.org/) will often have a BIOM file, associated with metadata files for samples and taxa.
Katherine will provide some example data for this combination.

**Comment by thomasstjerne** [comment]
This has now been implemented based on test data from K. Silliman from NOAA.

Users may now upload OTU tables in BIOM 2.1 (hdf5) format. These can be associated with txt/tsv/csv files describing Taxa/OTUs/ASVs and a sample file, even if these are contained in QIIME 2 artifacts (i.e. .qza files will be decompressed).
