### ISSUE TITLE
Works with Safari but not with Chrome

### ISSUE THREAD

**Issue by dagendresen** [gbif/metabarcoding-data-toolkit-ui#134]
Seems like some functionality works with Safari but not with Chrome

Chrome Version 128.0.6613.138 (Official Build) (x86_64) -- on a MacBook Pro with macOS Ventura Version 13.7 (22H123)

I tried to add institutions and also tried to add users. Hit the save button (or similar) and was repeatedly just logged out when using Chrome. Was working fine when using Safari.

**Comment by thomasstjerne** [comment]
Hi @dagendresen 

If you got logged out, could you maybe specify which button in the MDT you hit? - and your Chrome version?

Thanks
Thomas

**Comment by dagendresen** [comment]
Tried again with a fresh updated Chrome browser, Version 129.0.6668.101 (Official Build) (x86_64), and now I can add users without being logged out (to institutions UiO and UiB in the MDT).
Niels wrote by email that he also now can add users (to institution Naturalis) without being logged out.

**Comment by timrobertson100** [comment]
Thank Dag.

I notice others have reported [lost headers using Axios](https://github.com/axios/axios/issues/5761) but that it appears environment related. This appears(?) to be a bug in Chrome.
