### ISSUE TITLE
Set up GBIF installations / environments

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/metabarcoding-data-toolkit-ui#137]
I think we have agreed that:

1. We want a conversion only demo installed in PROD at https://mdt.gbif.org/  - we will link this from the tools menu at gbif.org. This is supposed to be used for real datasets that may not fit into any of the node installations. It will be easy to transfer a dataset from this one to any other prod installation if necessary.
2. The current https://mdt.gbif-uat.org/ should from now on be used for running test datasets, making experiments etc. This one can be wiped weekly or every now and again as we decide. We should change the url to e.g. https://sandbox-mdt.gbif-uat.org/. We will from now on use prod logins on this one to avoid confusion for users. 

- [x] Email selected users that may have datasets they want to keep at https://mdt.gbif-uat.org/ - if they want to keep it, they should provide their gbif PROD login (if not the same as their UAT) (**Tobias**)
- [x] Create the prod installation (**Matt**)
- [x] Change UAT url from https://mdt.gbif-uat.org/  to https://mdt.gbif-test.org/  (**Matt**)
- [x] Transfer selected datasets and update users to prod (**Thomas**)
- [x] Wipe UAT, and start using PROD logins (**Thomas**)

**Comment by tobiasgf** [comment]
Suggestions for the titles and descriptions of the https://sandbox-mdt.gbif-uat.org/ and https://mdt.gbif.org/  

MDT Sandbox (Demo Installation)
This is a demo installation of the GBIF Metabarcoding Data Toolkit, configured to operate in conversion mode and publish only to the GBIF UAT (Test) environment. Please note that datasets in this environment are deleted weekly; therefore, avoid uploading important data without a backup.

If you need to process a real dataset and no other full-featured MDT installation is available, please use the GBIF Conversion MDT (LINK). This version is designed to handle dataset processing for potential publication to GBIF, with assistance available at the final step.

-----

GBIF Conversion MDT
This installation of the GBIF Metabarcoding Data Toolkit operates in conversion mode and publishes exclusively to the GBIF Test environment. It serves as an alternative when no other full-featured MDT installation is available, supporting dataset processing for eventual publication to GBIF. Users should request assistance at the final step (“Publish”) to complete this process.

For testing or learning purposes, please use the MDT Sandbox (Demo Installation) (LINK).

**Comment by tobiasgf** [comment]
The descriptions are too verbose, I think. Maybe revise to:

MDT Sandbox (Demo Installation)
A demo installation of the GBIF Metabarcoding Data Toolkit (MDT) for testing and training purposes. Datasets are deleted weekly, and it can only publish to the GBIF Test website (UAT). If you need to process a real dataset and no other full-featured MDT installation is available, please use the GBIF Conversion MDT.


GBIF Conversion MDT
This installation of the GBIF Metabarcoding Data Toolkit (MDT) is available for processing real datasets when no other full-featured MDT installation is available. For testing or training purposes, please use the MDT Sandbox (Demo Installation).

**Comment by tobiasgf** [comment]
@thomasstjerne : Is it easy to update the descriptions? Then I will update the guide with new URLs and new screenshots.
