### ISSUE TITLE
additional navigation tools for admins

### ISSUE THREAD

**Issue by sformel-usgs** [gbif/metabarcoding-data-toolkit-ui#140]
When I'm logged in as an admin, I can see all the datasets in the MDT, but I can't navigate to their editing UI.  

A handy feature would be to link the dataset on the admin page: https://mdt.gbif.us/admin
to the dataset editing page: https://mdt.gbif.us/dataset/6f86eea3-54fd-4f4a-b661-13340c14666d/upload

One suggestion would be to make the dataset title a link to the editing page. Another would be to add an `edit` button/link.

**Comment by thomasstjerne** [comment]
Thanks @sformel-usgs 
Would you also expect - as an admin - to be able to do editing? Or only view the editing steps?

Currently, it is only the user who "owns" the dataset that can edit data.

**Comment by tobiasgf** [comment]
(Disclaimer: I am not fully familiar with all IPT functionalities).
I would also think that it would be valuable for MDT managers to assist in formatting/correcting/enriching datasets in the MDT. If such "un-tracked" co-editing (maybe also by other collaborators/users, not just MDT manager) is not in conflict with any guidelines or rules, and it aligns with IPT functionalities/possibilities, then I see no reason not to allow that in the MDT (if possible).

Also, it might not be good to have editing rights exclusively for "potentially ephemeral data publisher" (master students etc)?

**Comment by sformel-usgs** [comment]
> Also, it might not be good to have editing rights exclusively for "potentially ephemeral data publisher" (master students etc)?

Good call. If admins have these permissions by default, then it implies that they become a data steward if the provider disappears. That will free us up to make decisions in place of an unresponsive provider.

**Comment by thomasstjerne** [comment]
Thanks Steve.
I will look into this. It requires a little work since I want log who did what and when on a dataset. This should be written that to the log file.
we might face situations where either the admin or the user wasn´t aware that another person altered the dataset and then it would be nice to have an audit trail of some sort.
