### ISSUE TITLE
include validation logs during export creation

### ISSUE THREAD

**Issue by sformel-usgs** [gbif/metabarcoding-data-toolkit-ui#142]
It's not clear if the archive.zip file produced by the MDT is validated or not. It would be my preference for it to be validated at this stage, not publishing.

The user guide makes it clear that [validation can happen through the IPT](https://docs.gbif-uat.org/mdt-user-guide/en/index.en.html#publish-through-ipt), but it's not clear if that will happen through the MDT, although I realize the guide is still in development.  Also, as an admin I find the publication logs the IPT produces to be very valuable for troubleshooting. Whether these are created at the export or publication step, I hope they can be available to the user and admins.

**Comment by thomasstjerne** [comment]
Thanks @sformel-usgs 
I have added logs to the datasets in the admin section.
There are some fundamental differences in how the MDT vs the IPT works. In the MDT there is an option to do a test ingestion in the GBIF UAT environment which will provide a full interpretation of the DWC archive.

In the MDT, there is not much validation of the EML so far, but again, the UAT ingested dataset should give a pretty good idea of how the final publication will appear.
