### ISSUE TITLE
Implement "fuzzy matching" of ID fields (OTUs and Samples)

### ISSUE THREAD

**Issue by tobiasgf** [gbif/metabarcoding-data-toolkit-ui#146]
We often see that users do not use the required label "id" for the ID field in the OTU_table and and the Samples table. They may have a plan to map a field later in the procedure, but for new users it is often confusing to see a message like this when uploading: "_18 of 18 columns in the OTU table does not have a corresponding row in the sample file_"

I suggest to have recognized synonyms and fuzzy matching
It should be implemented at the upload page, in a way that the mechanisms are triggered _when no "id" is found._

**Mechanisms**
Step 1:
Synonyms (case insensitive, replacing non-letter characters with underscore or something?)
OTU: otu_id, seq_id,  ?
sample: sample_id, eventID (the DwC term), ... ?

Step 2: 
Fuzzy (could be using the first field with any of these words when scanning the labels, case insensitive)
OTU ID: "id", "asv", "otu", ?
Sample ID: (containing "id" AND not being a DwC term), "sample"

Potential step 3:
Use first field/column (but checking that it contains unique values only? and has an overlap with the names of the OTU table?)

Potential step 4 (or step 1?)
Use the row names and column names from the OTU table to scan for which field in Samples and OTU_table has those values, and pre-map those as id.

Report to user (in upload step after using the above mechanism):
"In the absence of the field "id", the field XXX was tentatively used as Sample/OTU IDs. You can change that in the next step (mapping) as needed"

**Comment by thomasstjerne** [comment]
Problem here is that we try to validate the structure (are there sampl ids not in the otu table etc) before we actually know the foreign key.
That why we decided that the id should just always be named `id`. However, we still have dropdowns to map the id to another field, and we can definately process files with arbitrary names for the `id`.
I am wondering whether we should just always assume the the id is the very first column (from left) of the sample file and taxonomy file?
Or we use a synonymy list like `samp_name, sample_name, samp_id, sample_id, process_id" etc etc.
