### ISSUE TITLE
Maybe offer to run ScientificName through name parser

### ISSUE THREAD

**Issue by tobiasgf** [gbif/metabarcoding-data-toolkit-ui#31]
As a user it is presently impossible to know is any of the names will be understood during ingestion. And the complete taxonomic charts during review may give the false impression that all is good. If e.g. 
I suggest to offer (or as default) to parse ScientificName through the [name parser](https://www.gbif.org/tools/name-parser), and provide the user with some breakdown stats and possibility to get a full list.

**Comment by tobiasgf** [comment]
There is a similar wish to get a pre-view of how the taxonomy looks from the OBIS/WoRMS perspective.

**Comment by thomasstjerne** [comment]
Also suggested by Katherine Silliman at the call on 18th Jul
