### ISSUE TITLE
Publication workflow

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/metabarcoding-data-toolkit-ui#62]
**In order to provide a smooth "one stop" data publishing experience for individual researchers, we will implement the following:**

- [ ] We move the tool to prod environment (so that archives produced with the tool are in a stable environment)
- [x] When a user has processed and formatted a dataset in the tool, they will be met with the button: “show/publish dataset in GBIF test environment”.
- [x] They will get a pop-up informing that it takes some time to ingest the dataset and show occurrences and events (as is now).
- [ ] They will somehow (we need to decide how) get the option to proceed to proper publishing (production env).
- [ ] We establish a default publisher (what should the name be?). This publisher will initially be both the hosting organisation and the publishing organisation.
- [ ] If the user wants to proceed with publishing to production env, they will fill in a form where they accept terms and confirm they have the right to publish the data. The form will also give an option to search and select a publishing organisation that they think should be the publisher of the data. If a publishing organisation is not existing already, they can fill in name, address and contact email for a potential new publisher. 
- [ ] If the organisation is not already registered as publisher, it could be contacted and asked to consider being a publisher. The process / workflow for this and the responsibilities will have to be discussed and formalized
- [ ] The form submits with an email to [DNA@GBIF.org](mailto:DNA@GBIF.org) - or simply opens a mail link link with a pre-drafted email.
- [ ] When the form is finished, the dataset will be published to GBIF.org under the above mentioned publisher. The DWC endpoint will point to hosted-datasets.gbif.org.
- [ ]  [New endpoint types for the BIOM files](https://github.com/gbif/registry/issues/535) will also be registered for the dataset.

**Comment by tobiasgf** [comment]
This needs to be prioritized so we can roll-out this tool as a fully functional tool for "one-stop" publishing as soon as possible.
